project_id = "osgadmygrprapwakfidr"

[functions.check-offline-devices]
verify_jwt = false

[functions.agent-enroll]
verify_jwt = false

[functions.agent-heartbeat]
verify_jwt = false

[functions.agent-screenshot]
verify_jwt = false

[functions.agent-events]
verify_jwt = false

[functions.send-alert-email]
verify_jwt = true